name: simplabs.com

sass:
  sass_dir: css

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

excerpt_separator: <!--break-->
  
navigation:
  - title: Services
    url: /services/
  - title: Process
    url: /process/
  - title: Workshops
    url: /workshops/
  - title: About
    url: /about/
  - title: Clients
    url: /clients/
  - title: Blog
    url: /blog/

title: simplabs
author: simplabs
description: simplabs builds solutions for the web and mobile devices

url: http://simplabs.com
logo: /images/apple-144.png

twitter:
  username: simplabs
facebook:
  publisher: https://www.facebook.com/simplabs/

exclude: [vendor]

defaults:
  -
    scope:
      path: ""
    values:
      image: 
        twitter: /images/apple-144.png
        facebook: /images/apple-144.png
        height: 144
        width: 144
