name: simplabs.com

sass:
  sass_dir: css

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

excerpt_separator: <!--break-->

navigation:
  - title: Services
    url: /services/
  - title: Work
    url: /work/
  - title: Training
    url: /training/
  - title: About
    url: /about/

title: simplabs
author: simplabs
description: Solid engineering for ambitious projects

url: http://simplabs.com
logo: /images/apple-144.png

twitter:
  username: simplabs
facebook:
  publisher: https://www.facebook.com/simplabs/

exclude: [vendor]

defaults:
  -
    scope:
      path: ""
    values:
      image:
        twitter: /images/apple-144.png
        facebook: /images/apple-144.png
        height: 144
        width: 144

